// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: apis/serviceconn/gateway_file_service/pb/gw_file_svc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadBlogFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlogId   string `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	FileName string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // int64 id = 4;
}

func (x *UploadBlogFileReq) Reset() {
	*x = UploadBlogFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadBlogFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBlogFileReq) ProtoMessage() {}

func (x *UploadBlogFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBlogFileReq.ProtoReflect.Descriptor instead.
func (*UploadBlogFileReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{0}
}

func (x *UploadBlogFileReq) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *UploadBlogFileReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadBlogFileReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type UploadBlogFileRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error       string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id          int64  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	NewFileName string `protobuf:"bytes,4,opt,name=new_file_name,json=newFileName,proto3" json:"new_file_name,omitempty"`
}

func (x *UploadBlogFileRes) Reset() {
	*x = UploadBlogFileRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadBlogFileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBlogFileRes) ProtoMessage() {}

func (x *UploadBlogFileRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBlogFileRes.ProtoReflect.Descriptor instead.
func (*UploadBlogFileRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{1}
}

func (x *UploadBlogFileRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UploadBlogFileRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UploadBlogFileRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UploadBlogFileRes) GetNewFileName() string {
	if x != nil {
		return x.NewFileName
	}
	return ""
}

type GetBlogFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlogId   string `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *GetBlogFileReq) Reset() {
	*x = GetBlogFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogFileReq) ProtoMessage() {}

func (x *GetBlogFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogFileReq.ProtoReflect.Descriptor instead.
func (*GetBlogFileReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlogFileReq) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *GetBlogFileReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetBlogFileRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status int64  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetBlogFileRes) Reset() {
	*x = GetBlogFileRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogFileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogFileRes) ProtoMessage() {}

func (x *GetBlogFileRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogFileRes.ProtoReflect.Descriptor instead.
func (*GetBlogFileRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlogFileRes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetBlogFileRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetBlogFileRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteBlogFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlogId   string `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *DeleteBlogFileReq) Reset() {
	*x = DeleteBlogFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlogFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogFileReq) ProtoMessage() {}

func (x *DeleteBlogFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogFileReq.ProtoReflect.Descriptor instead.
func (*DeleteBlogFileReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBlogFileReq) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *DeleteBlogFileReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type DeleteBlogFileRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status  int64  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteBlogFileRes) Reset() {
	*x = DeleteBlogFileRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlogFileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogFileRes) ProtoMessage() {}

func (x *DeleteBlogFileRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogFileRes.ProtoReflect.Descriptor instead.
func (*DeleteBlogFileRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBlogFileRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteBlogFileRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteBlogFileRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UploadProfilePicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileType string `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
}

func (x *UploadProfilePicReq) Reset() {
	*x = UploadProfilePicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadProfilePicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProfilePicReq) ProtoMessage() {}

func (x *UploadProfilePicReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProfilePicReq.ProtoReflect.Descriptor instead.
func (*UploadProfilePicReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{6}
}

func (x *UploadProfilePicReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadProfilePicReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadProfilePicReq) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type UploadProfilePicRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	FileName string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *UploadProfilePicRes) Reset() {
	*x = UploadProfilePicRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadProfilePicRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProfilePicRes) ProtoMessage() {}

func (x *UploadProfilePicRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProfilePicRes.ProtoReflect.Descriptor instead.
func (*UploadProfilePicRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{7}
}

func (x *UploadProfilePicRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UploadProfilePicRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UploadProfilePicRes) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetProfilePicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *GetProfilePicReq) Reset() {
	*x = GetProfilePicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProfilePicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilePicReq) ProtoMessage() {}

func (x *GetProfilePicReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilePicReq.ProtoReflect.Descriptor instead.
func (*GetProfilePicReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfilePicReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProfilePicReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetProfilePicRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetProfilePicRes) Reset() {
	*x = GetProfilePicRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProfilePicRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilePicRes) ProtoMessage() {}

func (x *GetProfilePicRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilePicRes.ProtoReflect.Descriptor instead.
func (*GetProfilePicRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{9}
}

func (x *GetProfilePicRes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetProfilePicRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetProfilePicRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteProfilePicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *DeleteProfilePicReq) Reset() {
	*x = DeleteProfilePicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProfilePicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfilePicReq) ProtoMessage() {}

func (x *DeleteProfilePicReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfilePicReq.ProtoReflect.Descriptor instead.
func (*DeleteProfilePicReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProfilePicReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteProfilePicReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type DeleteProfilePicRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status  int64  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteProfilePicRes) Reset() {
	*x = DeleteProfilePicRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProfilePicRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfilePicRes) ProtoMessage() {}

func (x *DeleteProfilePicRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfilePicRes.ProtoReflect.Descriptor instead.
func (*DeleteProfilePicRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteProfilePicRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteProfilePicRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteProfilePicRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto protoreflect.FileDescriptor

var file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x63, 0x6f,
	0x6e, 0x6e, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x77, 0x5f, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x75,
	0x74, 0x68, 0x5f, 0x73, 0x76, 0x63, 0x22, 0x5d, 0x0a, 0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x42, 0x6c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x62,
	0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6c,
	0x6f, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x75, 0x0a, 0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42,
	0x6c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x5f,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x6e, 0x65, 0x77, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x46, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17,
	0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x62, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x52, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x49, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x07, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x62, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f,
	0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x5f, 0x0a, 0x13, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x60, 0x0a, 0x13, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x56, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x52, 0x65,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4b, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x5d, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x32, 0xec, 0x03, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x67,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x54, 0x0a, 0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x12, 0x1d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x5f,
	0x73, 0x76, 0x63, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73,
	0x76, 0x63, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x50, 0x69, 0x63, 0x52, 0x65, 0x73, 0x22, 0x00, 0x28, 0x01, 0x12, 0x4b, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x12, 0x1a, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73,
	0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01, 0x12, 0x52, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x12, 0x1d, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1b, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42,
	0x6c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x67,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x28, 0x01, 0x12, 0x45, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73, 0x76, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x4c, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73, 0x76, 0x63, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x42, 0x2c, 0x5a, 0x2a, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescOnce sync.Once
	file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescData = file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDesc
)

func file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescGZIP() []byte {
	file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescOnce.Do(func() {
		file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescData)
	})
	return file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDescData
}

var file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_goTypes = []interface{}{
	(*UploadBlogFileReq)(nil),   // 0: auth_svc.UploadBlogFileReq
	(*UploadBlogFileRes)(nil),   // 1: auth_svc.UploadBlogFileRes
	(*GetBlogFileReq)(nil),      // 2: auth_svc.GetBlogFileReq
	(*GetBlogFileRes)(nil),      // 3: auth_svc.GetBlogFileRes
	(*DeleteBlogFileReq)(nil),   // 4: auth_svc.DeleteBlogFileReq
	(*DeleteBlogFileRes)(nil),   // 5: auth_svc.DeleteBlogFileRes
	(*UploadProfilePicReq)(nil), // 6: auth_svc.UploadProfilePicReq
	(*UploadProfilePicRes)(nil), // 7: auth_svc.UploadProfilePicRes
	(*GetProfilePicReq)(nil),    // 8: auth_svc.GetProfilePicReq
	(*GetProfilePicRes)(nil),    // 9: auth_svc.GetProfilePicRes
	(*DeleteProfilePicReq)(nil), // 10: auth_svc.DeleteProfilePicReq
	(*DeleteProfilePicRes)(nil), // 11: auth_svc.DeleteProfilePicRes
}
var file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_depIdxs = []int32{
	6,  // 0: auth_svc.UploadBlogFile.UploadProfilePic:input_type -> auth_svc.UploadProfilePicReq
	8,  // 1: auth_svc.UploadBlogFile.GetProfilePic:input_type -> auth_svc.GetProfilePicReq
	10, // 2: auth_svc.UploadBlogFile.DeleteProfilePic:input_type -> auth_svc.DeleteProfilePicReq
	0,  // 3: auth_svc.UploadBlogFile.UploadBlogFile:input_type -> auth_svc.UploadBlogFileReq
	2,  // 4: auth_svc.UploadBlogFile.GetBlogFile:input_type -> auth_svc.GetBlogFileReq
	4,  // 5: auth_svc.UploadBlogFile.DeleteBlogFile:input_type -> auth_svc.DeleteBlogFileReq
	7,  // 6: auth_svc.UploadBlogFile.UploadProfilePic:output_type -> auth_svc.UploadProfilePicRes
	9,  // 7: auth_svc.UploadBlogFile.GetProfilePic:output_type -> auth_svc.GetProfilePicRes
	11, // 8: auth_svc.UploadBlogFile.DeleteProfilePic:output_type -> auth_svc.DeleteProfilePicRes
	1,  // 9: auth_svc.UploadBlogFile.UploadBlogFile:output_type -> auth_svc.UploadBlogFileRes
	3,  // 10: auth_svc.UploadBlogFile.GetBlogFile:output_type -> auth_svc.GetBlogFileRes
	5,  // 11: auth_svc.UploadBlogFile.DeleteBlogFile:output_type -> auth_svc.DeleteBlogFileRes
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_init() }
func file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_init() {
	if File_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadBlogFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadBlogFileRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogFileRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlogFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlogFileRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadProfilePicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadProfilePicRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProfilePicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProfilePicRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProfilePicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProfilePicRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_goTypes,
		DependencyIndexes: file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_depIdxs,
		MessageInfos:      file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_msgTypes,
	}.Build()
	File_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto = out.File
	file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_rawDesc = nil
	file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_goTypes = nil
	file_apis_serviceconn_gateway_file_service_pb_gw_file_svc_proto_depIdxs = nil
}
