package constants

const (
	Register                     = "%s joined"
	Login                        = "%s logged in"
	ForgotPassword               = "%s accessed forgot password api"
	VerifiedEmailForPassChange   = "%s verified email to change the password"
	UpdatedPassword              = "%s updated the password"
	Logout                       = "Logged Out"
	UpdateProfile                = "Updated Profile"
	RequestForEmailVerification  = "%s requested Email Verification"
	VerifyEmail                  = "%s verified Email"
	UserStatusChange             = "Changed User Status"
	UserDeactivated              = "Deactivated User"
	UserActivated                = "Activated User"
	UpdateProfilePic             = "Updated Profile Picture"
	RemoveProfilePic             = "Removed Profile Picture"
	UpdatedUserName              = "Updated Username"
	ChangedEmail                 = "Changed Email"
	ChangedVisibilityToAnonymous = "Changed Visibility to Anonymous"
	ChangedVisibilityToPublic    = "Changed Visibility to Public"

	AddedInstagram = "Added Instagram"
	AddedTwitter   = "Added Twitter"

	DraftBlog                = "Drafted a Blog"
	UpdateDraftedBlog        = "Updated the Drafted Blog"
	UpdateBlog               = "Updated the Blog"
	DeleteBlog               = "Deleted the Blog"
	PublishBlog              = "Published the Blog"
	ArchiveBlog              = "Archived the Blog"
	LikeBlog                 = "Liked a Blog"
	UnlikeBlog               = "Disliked a Blog"
	CommentBlog              = "Commented on a Blog"
	ShareBlog                = "Shared a Blog with %s"
	TransferredBlogOwnership = "Transferred Blog Ownership to %s"
	InvitedAsACoAuthor       = "Invited %s as a Co-Author"
	RevokedCoAuthorRequest   = "Revoked as a Co-Author sent to %s"
	RemovedFromCoAuthor      = "Removed %s from Co-Author"
	GotInvitedAsACoAuthor    = "Invited by %s as a Co-Author"
	GotRemovedFromCoAuthor   = "Removed by %s form a Co-Author"
	DeclinedCoAuthor         = "Declined co-author request of %s"
	JoinedAsCoAuthor         = "Joined as a Co-Author"
	UpdatedABlogAsCoAuthor   = "Updated a Blog as a Co-Author"
	PublishedABlogAsCoAuthor = "Published a Blog as a Co-Author"
	ArchivedABlogAsCoAuthor  = "Archived a Blog as a Co-Author"
	DraftedABlogAsCoAuthor   = "Drafted a Blog as a Co-Author"
)
