// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: apis/grpc/fileserver/filleserver.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadProfilePicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileType string `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
}

func (x *UploadProfilePicReq) Reset() {
	*x = UploadProfilePicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_grpc_fileserver_filleserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadProfilePicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProfilePicReq) ProtoMessage() {}

func (x *UploadProfilePicReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_grpc_fileserver_filleserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProfilePicReq.ProtoReflect.Descriptor instead.
func (*UploadProfilePicReq) Descriptor() ([]byte, []int) {
	return file_apis_grpc_fileserver_filleserver_proto_rawDescGZIP(), []int{0}
}

func (x *UploadProfilePicReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadProfilePicReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadProfilePicReq) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type UploadProfilePicRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	FileName string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *UploadProfilePicRes) Reset() {
	*x = UploadProfilePicRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_grpc_fileserver_filleserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadProfilePicRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProfilePicRes) ProtoMessage() {}

func (x *UploadProfilePicRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_grpc_fileserver_filleserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProfilePicRes.ProtoReflect.Descriptor instead.
func (*UploadProfilePicRes) Descriptor() ([]byte, []int) {
	return file_apis_grpc_fileserver_filleserver_proto_rawDescGZIP(), []int{1}
}

func (x *UploadProfilePicRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UploadProfilePicRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UploadProfilePicRes) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetProfilePicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *GetProfilePicReq) Reset() {
	*x = GetProfilePicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_grpc_fileserver_filleserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProfilePicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilePicReq) ProtoMessage() {}

func (x *GetProfilePicReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_grpc_fileserver_filleserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilePicReq.ProtoReflect.Descriptor instead.
func (*GetProfilePicReq) Descriptor() ([]byte, []int) {
	return file_apis_grpc_fileserver_filleserver_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfilePicReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProfilePicReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetProfilePicRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetProfilePicRes) Reset() {
	*x = GetProfilePicRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_grpc_fileserver_filleserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProfilePicRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilePicRes) ProtoMessage() {}

func (x *GetProfilePicRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_grpc_fileserver_filleserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilePicRes.ProtoReflect.Descriptor instead.
func (*GetProfilePicRes) Descriptor() ([]byte, []int) {
	return file_apis_grpc_fileserver_filleserver_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfilePicRes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetProfilePicRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetProfilePicRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteProfilePicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *DeleteProfilePicReq) Reset() {
	*x = DeleteProfilePicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_grpc_fileserver_filleserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProfilePicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfilePicReq) ProtoMessage() {}

func (x *DeleteProfilePicReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_grpc_fileserver_filleserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfilePicReq.ProtoReflect.Descriptor instead.
func (*DeleteProfilePicReq) Descriptor() ([]byte, []int) {
	return file_apis_grpc_fileserver_filleserver_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteProfilePicReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteProfilePicReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type DeleteProfilePicRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status  int64  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteProfilePicRes) Reset() {
	*x = DeleteProfilePicRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_grpc_fileserver_filleserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProfilePicRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfilePicRes) ProtoMessage() {}

func (x *DeleteProfilePicRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_grpc_fileserver_filleserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfilePicRes.ProtoReflect.Descriptor instead.
func (*DeleteProfilePicRes) Descriptor() ([]byte, []int) {
	return file_apis_grpc_fileserver_filleserver_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProfilePicRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteProfilePicRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteProfilePicRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_apis_grpc_fileserver_filleserver_proto protoreflect.FileDescriptor

var file_apis_grpc_fileserver_filleserver_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x5f,
	0x0a, 0x13, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50,
	0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x60, 0x0a, 0x13, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x50, 0x69, 0x63, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x48, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50,
	0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x56, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x4b, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x5d, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32,
	0xec, 0x01, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4c, 0x0a, 0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x50, 0x69, 0x63, 0x12, 0x19, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x19,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x73, 0x22, 0x00, 0x28, 0x01, 0x12, 0x43, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x12, 0x16,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x4a, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x12, 0x19, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x1b,
	0x5a, 0x19, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_apis_grpc_fileserver_filleserver_proto_rawDescOnce sync.Once
	file_apis_grpc_fileserver_filleserver_proto_rawDescData = file_apis_grpc_fileserver_filleserver_proto_rawDesc
)

func file_apis_grpc_fileserver_filleserver_proto_rawDescGZIP() []byte {
	file_apis_grpc_fileserver_filleserver_proto_rawDescOnce.Do(func() {
		file_apis_grpc_fileserver_filleserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_grpc_fileserver_filleserver_proto_rawDescData)
	})
	return file_apis_grpc_fileserver_filleserver_proto_rawDescData
}

var file_apis_grpc_fileserver_filleserver_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apis_grpc_fileserver_filleserver_proto_goTypes = []interface{}{
	(*UploadProfilePicReq)(nil), // 0: auth.UploadProfilePicReq
	(*UploadProfilePicRes)(nil), // 1: auth.UploadProfilePicRes
	(*GetProfilePicReq)(nil),    // 2: auth.GetProfilePicReq
	(*GetProfilePicRes)(nil),    // 3: auth.GetProfilePicRes
	(*DeleteProfilePicReq)(nil), // 4: auth.DeleteProfilePicReq
	(*DeleteProfilePicRes)(nil), // 5: auth.DeleteProfilePicRes
}
var file_apis_grpc_fileserver_filleserver_proto_depIdxs = []int32{
	0, // 0: auth.FileService.UploadProfilePic:input_type -> auth.UploadProfilePicReq
	2, // 1: auth.FileService.GetProfilePic:input_type -> auth.GetProfilePicReq
	4, // 2: auth.FileService.DeleteProfilePic:input_type -> auth.DeleteProfilePicReq
	1, // 3: auth.FileService.UploadProfilePic:output_type -> auth.UploadProfilePicRes
	3, // 4: auth.FileService.GetProfilePic:output_type -> auth.GetProfilePicRes
	5, // 5: auth.FileService.DeleteProfilePic:output_type -> auth.DeleteProfilePicRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apis_grpc_fileserver_filleserver_proto_init() }
func file_apis_grpc_fileserver_filleserver_proto_init() {
	if File_apis_grpc_fileserver_filleserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_grpc_fileserver_filleserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadProfilePicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_grpc_fileserver_filleserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadProfilePicRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_grpc_fileserver_filleserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProfilePicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_grpc_fileserver_filleserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProfilePicRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_grpc_fileserver_filleserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProfilePicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_grpc_fileserver_filleserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProfilePicRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_grpc_fileserver_filleserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_grpc_fileserver_filleserver_proto_goTypes,
		DependencyIndexes: file_apis_grpc_fileserver_filleserver_proto_depIdxs,
		MessageInfos:      file_apis_grpc_fileserver_filleserver_proto_msgTypes,
	}.Build()
	File_apis_grpc_fileserver_filleserver_proto = out.File
	file_apis_grpc_fileserver_filleserver_proto_rawDesc = nil
	file_apis_grpc_fileserver_filleserver_proto_goTypes = nil
	file_apis_grpc_fileserver_filleserver_proto_depIdxs = nil
}
