// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: services/api_gateway/pkg/blogsandposts/pb/blogsandposts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBlogRequest_Ownership int32

const (
	CreateBlogRequest_THE_USER    CreateBlogRequest_Ownership = 0
	CreateBlogRequest_THE_MONKEYS CreateBlogRequest_Ownership = 1
	CreateBlogRequest_THE_PARTNER CreateBlogRequest_Ownership = 2
)

// Enum value maps for CreateBlogRequest_Ownership.
var (
	CreateBlogRequest_Ownership_name = map[int32]string{
		0: "THE_USER",
		1: "THE_MONKEYS",
		2: "THE_PARTNER",
	}
	CreateBlogRequest_Ownership_value = map[string]int32{
		"THE_USER":    0,
		"THE_MONKEYS": 1,
		"THE_PARTNER": 2,
	}
)

func (x CreateBlogRequest_Ownership) Enum() *CreateBlogRequest_Ownership {
	p := new(CreateBlogRequest_Ownership)
	*p = x
	return p
}

func (x CreateBlogRequest_Ownership) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateBlogRequest_Ownership) Descriptor() protoreflect.EnumDescriptor {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_enumTypes[0].Descriptor()
}

func (CreateBlogRequest_Ownership) Type() protoreflect.EnumType {
	return &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_enumTypes[0]
}

func (x CreateBlogRequest_Ownership) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateBlogRequest_Ownership.Descriptor instead.
func (CreateBlogRequest_Ownership) EnumDescriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{0, 0}
}

type BlogRequest_Ownership int32

const (
	BlogRequest_THE_USER    BlogRequest_Ownership = 0
	BlogRequest_THE_MONKEYS BlogRequest_Ownership = 1
	BlogRequest_THE_PARTNER BlogRequest_Ownership = 2
)

// Enum value maps for BlogRequest_Ownership.
var (
	BlogRequest_Ownership_name = map[int32]string{
		0: "THE_USER",
		1: "THE_MONKEYS",
		2: "THE_PARTNER",
	}
	BlogRequest_Ownership_value = map[string]int32{
		"THE_USER":    0,
		"THE_MONKEYS": 1,
		"THE_PARTNER": 2,
	}
)

func (x BlogRequest_Ownership) Enum() *BlogRequest_Ownership {
	p := new(BlogRequest_Ownership)
	*p = x
	return p
}

func (x BlogRequest_Ownership) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlogRequest_Ownership) Descriptor() protoreflect.EnumDescriptor {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_enumTypes[1].Descriptor()
}

func (BlogRequest_Ownership) Type() protoreflect.EnumType {
	return &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_enumTypes[1]
}

func (x BlogRequest_Ownership) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlogRequest_Ownership.Descriptor instead.
func (BlogRequest_Ownership) EnumDescriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{11, 0}
}

type CreateBlogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title      string                      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content    string                      `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorName string                      `protobuf:"bytes,4,opt,name=authorName,proto3" json:"authorName,omitempty"`
	AuthorId   string                      `protobuf:"bytes,5,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Published  bool                        `protobuf:"varint,6,opt,name=published,proto3" json:"published,omitempty"`
	Tags       []string                    `protobuf:"bytes,7,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Ownership  CreateBlogRequest_Ownership `protobuf:"varint,8,opt,name=ownership,proto3,enum=auth.CreateBlogRequest_Ownership" json:"ownership,omitempty"`
	CanEdit    bool                        `protobuf:"varint,9,opt,name=canEdit,proto3" json:"canEdit,omitempty"`
	FolderPath string                      `protobuf:"bytes,10,opt,name=folderPath,proto3" json:"folderPath,omitempty"`
	CreateTime *timestamppb.Timestamp      `protobuf:"bytes,11,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime *timestamppb.Timestamp      `protobuf:"bytes,12,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
}

func (x *CreateBlogRequest) Reset() {
	*x = CreateBlogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogRequest) ProtoMessage() {}

func (x *CreateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogRequest.ProtoReflect.Descriptor instead.
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBlogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateBlogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBlogRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateBlogRequest) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *CreateBlogRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreateBlogRequest) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

func (x *CreateBlogRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateBlogRequest) GetOwnership() CreateBlogRequest_Ownership {
	if x != nil {
		return x.Ownership
	}
	return CreateBlogRequest_THE_USER
}

func (x *CreateBlogRequest) GetCanEdit() bool {
	if x != nil {
		return x.CanEdit
	}
	return false
}

func (x *CreateBlogRequest) GetFolderPath() string {
	if x != nil {
		return x.FolderPath
	}
	return ""
}

func (x *CreateBlogRequest) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *CreateBlogRequest) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type CreateBlogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id     int64  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateBlogResponse) Reset() {
	*x = CreateBlogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogResponse) ProtoMessage() {}

func (x *CreateBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogResponse.ProtoReflect.Descriptor instead.
func (*CreateBlogResponse) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBlogResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateBlogResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateBlogResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBlogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBlogsRequest) Reset() {
	*x = GetBlogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsRequest) ProtoMessage() {}

func (x *GetBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsRequest.ProtoReflect.Descriptor instead.
func (*GetBlogsRequest) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{2}
}

type GetBlogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title      string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AuthorName string                 `protobuf:"bytes,3,opt,name=authorName,proto3" json:"authorName,omitempty"`
	AuthorId   string                 `protobuf:"bytes,4,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Content    string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
}

func (x *GetBlogsResponse) Reset() {
	*x = GetBlogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsResponse) ProtoMessage() {}

func (x *GetBlogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsResponse.ProtoReflect.Descriptor instead.
func (*GetBlogsResponse) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlogsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBlogsResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetBlogsResponse) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *GetBlogsResponse) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *GetBlogsResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetBlogsResponse) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type GetBlogByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *GetBlogByIdRequest) Reset() {
	*x = GetBlogByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogByIdRequest) ProtoMessage() {}

func (x *GetBlogByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBlogByIdRequest) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlogByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBlogByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title      string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AuthorName string                 `protobuf:"bytes,3,opt,name=authorName,proto3" json:"authorName,omitempty"`
	AuthorId   string                 `protobuf:"bytes,4,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Content    string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Tags       []string               `protobuf:"bytes,7,rep,name=Tags,proto3" json:"Tags,omitempty"`
}

func (x *GetBlogByIdResponse) Reset() {
	*x = GetBlogByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogByIdResponse) ProtoMessage() {}

func (x *GetBlogByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogByIdResponse.ProtoReflect.Descriptor instead.
func (*GetBlogByIdResponse) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{5}
}

func (x *GetBlogByIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBlogByIdResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetBlogByIdResponse) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *GetBlogByIdResponse) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *GetBlogByIdResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetBlogByIdResponse) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *GetBlogByIdResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type EditBlogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title     string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content   string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Tags      []string `protobuf:"bytes,5,rep,name=Tags,proto3" json:"Tags,omitempty"`
	IsPartial bool     `protobuf:"varint,4,opt,name=isPartial,proto3" json:"isPartial,omitempty"`
}

func (x *EditBlogRequest) Reset() {
	*x = EditBlogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditBlogRequest) ProtoMessage() {}

func (x *EditBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditBlogRequest.ProtoReflect.Descriptor instead.
func (*EditBlogRequest) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{6}
}

func (x *EditBlogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditBlogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditBlogRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EditBlogRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EditBlogRequest) GetIsPartial() bool {
	if x != nil {
		return x.IsPartial
	}
	return false
}

type EditBlogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id     string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EditBlogResponse) Reset() {
	*x = EditBlogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditBlogResponse) ProtoMessage() {}

func (x *EditBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditBlogResponse.ProtoReflect.Descriptor instead.
func (*EditBlogResponse) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{7}
}

func (x *EditBlogResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EditBlogResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EditBlogResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBlogByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *DeleteBlogByIdRequest) Reset() {
	*x = DeleteBlogByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlogByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogByIdRequest) ProtoMessage() {}

func (x *DeleteBlogByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlogByIdRequest) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteBlogByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBlogByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id     int64  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBlogByIdResponse) Reset() {
	*x = DeleteBlogByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlogByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogByIdResponse) ProtoMessage() {}

func (x *DeleteBlogByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlogByIdResponse) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBlogByIdResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteBlogByIdResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeleteBlogByIdResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBlogsByTagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagName string `protobuf:"bytes,1,opt,name=tagName,proto3" json:"tagName,omitempty"`
}

func (x *GetBlogsByTagReq) Reset() {
	*x = GetBlogsByTagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlogsByTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogsByTagReq) ProtoMessage() {}

func (x *GetBlogsByTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogsByTagReq.ProtoReflect.Descriptor instead.
func (*GetBlogsByTagReq) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{10}
}

func (x *GetBlogsByTagReq) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

type BlogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HTMLContent  string                 `protobuf:"bytes,2,opt,name=HTMLContent,proto3" json:"HTMLContent,omitempty"`
	RawContent   string                 `protobuf:"bytes,3,opt,name=rawContent,proto3" json:"rawContent,omitempty"`
	CreateTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	AuthorName   string                 `protobuf:"bytes,6,opt,name=authorName,proto3" json:"authorName,omitempty"`
	AuthorEmail  string                 `protobuf:"bytes,7,opt,name=authorEmail,proto3" json:"authorEmail,omitempty"`
	AuthorStatus string                 `protobuf:"bytes,8,opt,name=authorStatus,proto3" json:"authorStatus,omitempty"`
	Published    bool                   `protobuf:"varint,9,opt,name=published,proto3" json:"published,omitempty"`
	Tags         []string               `protobuf:"bytes,10,rep,name=Tags,proto3" json:"Tags,omitempty"`
	CanEdit      bool                   `protobuf:"varint,11,opt,name=canEdit,proto3" json:"canEdit,omitempty"`
	Ownership    BlogRequest_Ownership  `protobuf:"varint,12,opt,name=ownership,proto3,enum=auth.BlogRequest_Ownership" json:"ownership,omitempty"`
	Category     string                 `protobuf:"bytes,13,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *BlogRequest) Reset() {
	*x = BlogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogRequest) ProtoMessage() {}

func (x *BlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogRequest.ProtoReflect.Descriptor instead.
func (*BlogRequest) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{11}
}

func (x *BlogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlogRequest) GetHTMLContent() string {
	if x != nil {
		return x.HTMLContent
	}
	return ""
}

func (x *BlogRequest) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *BlogRequest) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *BlogRequest) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *BlogRequest) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *BlogRequest) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *BlogRequest) GetAuthorStatus() string {
	if x != nil {
		return x.AuthorStatus
	}
	return ""
}

func (x *BlogRequest) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

func (x *BlogRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BlogRequest) GetCanEdit() bool {
	if x != nil {
		return x.CanEdit
	}
	return false
}

func (x *BlogRequest) GetOwnership() BlogRequest_Ownership {
	if x != nil {
		return x.Ownership
	}
	return BlogRequest_THE_USER
}

func (x *BlogRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type BlogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocId   string `protobuf:"bytes,1,opt,name=docId,proto3" json:"docId,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *BlogResponse) Reset() {
	*x = BlogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogResponse) ProtoMessage() {}

func (x *BlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogResponse.ProtoReflect.Descriptor instead.
func (*BlogResponse) Descriptor() ([]byte, []int) {
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP(), []int{12}
}

func (x *BlogResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *BlogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BlogResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto protoreflect.FileDescriptor

var file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDesc = []byte{
	0x0a, 0x3d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x73,
	0x61, 0x6e, 0x64, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x6c, 0x6f, 0x67,
	0x73, 0x61, 0x6e, 0x64, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xf1, 0x03, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c,
	0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x12, 0x3f, 0x0a, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x09, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x6e, 0x45,
	0x64, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x61, 0x6e, 0x45, 0x64,
	0x69, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x50, 0x61, 0x74, 0x68,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3a,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x09, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x48, 0x45, 0x5f, 0x55,
	0x53, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x48, 0x45, 0x5f, 0x4d, 0x4f, 0x4e,
	0x4b, 0x45, 0x59, 0x53, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x48, 0x45, 0x5f, 0x50, 0x41,
	0x52, 0x54, 0x4e, 0x45, 0x52, 0x10, 0x02, 0x22, 0x52, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xca,
	0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x3a, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x24, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x64, 0x22, 0xe1, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x54, 0x61, 0x67, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x0f, 0x45, 0x64, 0x69, 0x74, 0x42, 0x6c,
	0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x67,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x73, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x69, 0x73, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x50, 0x0a, 0x10, 0x45,
	0x64, 0x69, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a,
	0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0x56, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x9d, 0x04, 0x0a,
	0x0b, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x48, 0x54, 0x4d, 0x4c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x48, 0x54, 0x4d, 0x4c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x3a,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61,
	0x67, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x61, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x63, 0x61, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x73, 0x68, 0x69, 0x70, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73,
	0x68, 0x69, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22,
	0x3b, 0x0a, 0x09, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x0c, 0x0a, 0x08,
	0x54, 0x48, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x48,
	0x45, 0x5f, 0x4d, 0x4f, 0x4e, 0x4b, 0x45, 0x59, 0x53, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x54,
	0x48, 0x45, 0x5f, 0x50, 0x41, 0x52, 0x54, 0x4e, 0x45, 0x52, 0x10, 0x02, 0x22, 0x54, 0x0a, 0x0c,
	0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x64, 0x6f, 0x63, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x63,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x32, 0xf3, 0x03, 0x0a, 0x13, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x41, 0x6e, 0x64, 0x50,
	0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x42, 0x6c, 0x6f, 0x67, 0x12, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x31, 0x30, 0x30, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x44, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64,
	0x12, 0x18, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0c, 0x45, 0x64, 0x69, 0x74, 0x42,
	0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x12, 0x15, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x45,
	0x64, 0x69, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1b, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x6c,
	0x6f, 0x67, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x12, 0x16, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71,
	0x1a, 0x16, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3a, 0x0a, 0x0f,
	0x44, 0x72, 0x61, 0x66, 0x74, 0x41, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12,
	0x11, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x2e, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x61, 0x6e, 0x64, 0x70,
	0x6f, 0x73, 0x74, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescOnce sync.Once
	file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescData = file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDesc
)

func file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescGZIP() []byte {
	file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescOnce.Do(func() {
		file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescData)
	})
	return file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDescData
}

var file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_goTypes = []interface{}{
	(CreateBlogRequest_Ownership)(0), // 0: auth.CreateBlogRequest.Ownership
	(BlogRequest_Ownership)(0),       // 1: auth.BlogRequest.Ownership
	(*CreateBlogRequest)(nil),        // 2: auth.CreateBlogRequest
	(*CreateBlogResponse)(nil),       // 3: auth.CreateBlogResponse
	(*GetBlogsRequest)(nil),          // 4: auth.GetBlogsRequest
	(*GetBlogsResponse)(nil),         // 5: auth.GetBlogsResponse
	(*GetBlogByIdRequest)(nil),       // 6: auth.GetBlogByIdRequest
	(*GetBlogByIdResponse)(nil),      // 7: auth.GetBlogByIdResponse
	(*EditBlogRequest)(nil),          // 8: auth.EditBlogRequest
	(*EditBlogResponse)(nil),         // 9: auth.EditBlogResponse
	(*DeleteBlogByIdRequest)(nil),    // 10: auth.DeleteBlogByIdRequest
	(*DeleteBlogByIdResponse)(nil),   // 11: auth.DeleteBlogByIdResponse
	(*GetBlogsByTagReq)(nil),         // 12: auth.GetBlogsByTagReq
	(*BlogRequest)(nil),              // 13: auth.BlogRequest
	(*BlogResponse)(nil),             // 14: auth.BlogResponse
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 16: google.protobuf.Empty
}
var file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_depIdxs = []int32{
	0,  // 0: auth.CreateBlogRequest.ownership:type_name -> auth.CreateBlogRequest.Ownership
	15, // 1: auth.CreateBlogRequest.createTime:type_name -> google.protobuf.Timestamp
	15, // 2: auth.CreateBlogRequest.updateTime:type_name -> google.protobuf.Timestamp
	15, // 3: auth.GetBlogsResponse.createTime:type_name -> google.protobuf.Timestamp
	15, // 4: auth.GetBlogByIdResponse.createTime:type_name -> google.protobuf.Timestamp
	15, // 5: auth.BlogRequest.createTime:type_name -> google.protobuf.Timestamp
	15, // 6: auth.BlogRequest.updateTime:type_name -> google.protobuf.Timestamp
	1,  // 7: auth.BlogRequest.ownership:type_name -> auth.BlogRequest.Ownership
	2,  // 8: auth.BlogsAndPostService.CreateABlog:input_type -> auth.CreateBlogRequest
	16, // 9: auth.BlogsAndPostService.Get100Blogs:input_type -> google.protobuf.Empty
	6,  // 10: auth.BlogsAndPostService.GetBlogById:input_type -> auth.GetBlogByIdRequest
	8,  // 11: auth.BlogsAndPostService.EditBlogById:input_type -> auth.EditBlogRequest
	10, // 12: auth.BlogsAndPostService.DeleteBlogById:input_type -> auth.DeleteBlogByIdRequest
	12, // 13: auth.BlogsAndPostService.GetBlogsByTag:input_type -> auth.GetBlogsByTagReq
	13, // 14: auth.BlogsAndPostService.DraftAndPublish:input_type -> auth.BlogRequest
	3,  // 15: auth.BlogsAndPostService.CreateABlog:output_type -> auth.CreateBlogResponse
	5,  // 16: auth.BlogsAndPostService.Get100Blogs:output_type -> auth.GetBlogsResponse
	7,  // 17: auth.BlogsAndPostService.GetBlogById:output_type -> auth.GetBlogByIdResponse
	9,  // 18: auth.BlogsAndPostService.EditBlogById:output_type -> auth.EditBlogResponse
	11, // 19: auth.BlogsAndPostService.DeleteBlogById:output_type -> auth.DeleteBlogByIdResponse
	5,  // 20: auth.BlogsAndPostService.GetBlogsByTag:output_type -> auth.GetBlogsResponse
	14, // 21: auth.BlogsAndPostService.DraftAndPublish:output_type -> auth.BlogResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_init() }
func file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_init() {
	if File_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBlogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBlogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditBlogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditBlogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlogByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlogByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlogsByTagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_goTypes,
		DependencyIndexes: file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_depIdxs,
		EnumInfos:         file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_enumTypes,
		MessageInfos:      file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_msgTypes,
	}.Build()
	File_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto = out.File
	file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_rawDesc = nil
	file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_goTypes = nil
	file_services_api_gateway_pkg_blogsandposts_pb_blogsandposts_proto_depIdxs = nil
}
