// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: apis/serviceconn/gateway_user/pb/gw_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserActivityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *UserActivityReq) Reset() {
	*x = UserActivityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivityReq) ProtoMessage() {}

func (x *UserActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivityReq.ProtoReflect.Descriptor instead.
func (*UserActivityReq) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserActivityReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserActivityReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserActivityReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserActivityRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType   string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ServiceType string                 `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Timestamp   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IpAddress   string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Description string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *UserActivityRes) Reset() {
	*x = UserActivityRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserActivityRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivityRes) ProtoMessage() {}

func (x *UserActivityRes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivityRes.ProtoReflect.Descriptor instead.
func (*UserActivityRes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserActivityRes) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *UserActivityRes) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *UserActivityRes) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *UserActivityRes) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *UserActivityRes) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_apis_serviceconn_gateway_user_pb_gw_user_proto protoreflect.FileDescriptor

var file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x63, 0x6f,
	0x6e, 0x6e, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2f,
	0x70, 0x62, 0x2f, 0x67, 0x77, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73, 0x76, 0x63, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x0f, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0xce, 0x01, 0x0a, 0x0f, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x70,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x5a, 0x0a, 0x0b, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12,
	0x19, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x2e, 0x2f, 0x61, 0x70, 0x69,
	0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x2f, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescOnce sync.Once
	file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescData = file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDesc
)

func file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescGZIP() []byte {
	file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescOnce.Do(func() {
		file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescData)
	})
	return file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDescData
}

var file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apis_serviceconn_gateway_user_pb_gw_user_proto_goTypes = []interface{}{
	(*UserActivityReq)(nil),       // 0: auth_svc.UserActivityReq
	(*UserActivityRes)(nil),       // 1: auth_svc.UserActivityRes
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_apis_serviceconn_gateway_user_pb_gw_user_proto_depIdxs = []int32{
	2, // 0: auth_svc.UserActivityRes.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: auth_svc.UserService.GetUserActivities:input_type -> auth_svc.UserActivityReq
	1, // 2: auth_svc.UserService.GetUserActivities:output_type -> auth_svc.UserActivityRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apis_serviceconn_gateway_user_pb_gw_user_proto_init() }
func file_apis_serviceconn_gateway_user_pb_gw_user_proto_init() {
	if File_apis_serviceconn_gateway_user_pb_gw_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserActivityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserActivityRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_serviceconn_gateway_user_pb_gw_user_proto_goTypes,
		DependencyIndexes: file_apis_serviceconn_gateway_user_pb_gw_user_proto_depIdxs,
		MessageInfos:      file_apis_serviceconn_gateway_user_pb_gw_user_proto_msgTypes,
	}.Build()
	File_apis_serviceconn_gateway_user_pb_gw_user_proto = out.File
	file_apis_serviceconn_gateway_user_pb_gw_user_proto_rawDesc = nil
	file_apis_serviceconn_gateway_user_pb_gw_user_proto_goTypes = nil
	file_apis_serviceconn_gateway_user_pb_gw_user_proto_depIdxs = nil
}
