// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: apis/serviceconn/gateway_blog/pb/gw_blog.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DraftBlogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OwnerAccountId string `protobuf:"bytes,2,opt,name=owner_account_id,json=ownerAccountId,proto3" json:"owner_account_id,omitempty"`
	Blog           *Blog  `protobuf:"bytes,3,opt,name=blog,proto3" json:"blog,omitempty"`
}

func (x *DraftBlogRequest) Reset() {
	*x = DraftBlogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DraftBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftBlogRequest) ProtoMessage() {}

func (x *DraftBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftBlogRequest.ProtoReflect.Descriptor instead.
func (*DraftBlogRequest) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDescGZIP(), []int{0}
}

func (x *DraftBlogRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *DraftBlogRequest) GetOwnerAccountId() string {
	if x != nil {
		return x.OwnerAccountId
	}
	return ""
}

func (x *DraftBlogRequest) GetBlog() *Blog {
	if x != nil {
		return x.Blog
	}
	return nil
}

type BlogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Blog    *Blog  `protobuf:"bytes,2,opt,name=blog,proto3" json:"blog,omitempty"`
}

func (x *BlogResponse) Reset() {
	*x = BlogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogResponse) ProtoMessage() {}

func (x *BlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogResponse.ProtoReflect.Descriptor instead.
func (*BlogResponse) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDescGZIP(), []int{1}
}

func (x *BlogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BlogResponse) GetBlog() *Blog {
	if x != nil {
		return x.Blog
	}
	return nil
}

type Blog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time   int64    `protobuf:"varint,1,opt,name=Time,proto3" json:"Time,omitempty"`
	Blocks []*Block `protobuf:"bytes,2,rep,name=Blocks,proto3" json:"Blocks,omitempty"`
}

func (x *Blog) Reset() {
	*x = Blog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog) ProtoMessage() {}

func (x *Blog) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog.ProtoReflect.Descriptor instead.
func (*Blog) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDescGZIP(), []int{2}
}

func (x *Blog) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Blog) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Data   *Data  `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Author string `protobuf:"bytes,4,opt,name=Author,proto3" json:"Author,omitempty"`
	Time   int64  `protobuf:"varint,5,opt,name=Time,proto3" json:"Time,omitempty"`
	Tunes  *Tunes `protobuf:"bytes,6,opt,name=Tunes,proto3" json:"Tunes,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDescGZIP(), []int{3}
}

func (x *Block) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Block) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Block) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Block) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Block) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Block) GetTunes() *Tunes {
	if x != nil {
		return x.Tunes
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDescGZIP(), []int{4}
}

func (x *Data) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Tunes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Footnotes []string `protobuf:"bytes,1,rep,name=Footnotes,proto3" json:"Footnotes,omitempty"`
}

func (x *Tunes) Reset() {
	*x = Tunes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tunes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tunes) ProtoMessage() {}

func (x *Tunes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tunes.ProtoReflect.Descriptor instead.
func (*Tunes) Descriptor() ([]byte, []int) {
	return file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDescGZIP(), []int{5}
}

func (x *Tunes) GetFootnotes() []string {
	if x != nil {
		return x.Footnotes
	}
	return nil
}

var File_apis_serviceconn_gateway_blog_pb_gw_blog_proto protoreflect.FileDescriptor

var file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x63, 0x6f,
	0x6e, 0x6e, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x62, 0x6c, 0x6f, 0x67, 0x2f,
	0x70, 0x62, 0x2f, 0x67, 0x77, 0x5f, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x76, 0x63, 0x22, 0x70, 0x0a, 0x10, 0x44, 0x72,
	0x61, 0x66, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x28,
	0x0a, 0x10, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x76,
	0x63, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x04, 0x62, 0x6c, 0x6f, 0x67, 0x22, 0x4c, 0x0a, 0x0c,
	0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x76, 0x63, 0x2e,
	0x42, 0x6c, 0x6f, 0x67, 0x52, 0x04, 0x62, 0x6c, 0x6f, 0x67, 0x22, 0x43, 0x0a, 0x04, 0x42, 0x6c,
	0x6f, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x76,
	0x63, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22,
	0xa2, 0x01, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x6c,
	0x6f, 0x67, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x25, 0x0a,
	0x05, 0x54, 0x75, 0x6e, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62,
	0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x54, 0x75, 0x6e, 0x65, 0x73, 0x52, 0x05, 0x54,
	0x75, 0x6e, 0x65, 0x73, 0x22, 0x1a, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x78, 0x74,
	0x22, 0x25, 0x0a, 0x05, 0x54, 0x75, 0x6e, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x6f, 0x6f,
	0x74, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x46, 0x6f,
	0x6f, 0x74, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x32, 0x4e, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x44, 0x72, 0x61, 0x66, 0x74, 0x42,
	0x6c, 0x6f, 0x67, 0x12, 0x1a, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x44,
	0x72, 0x61, 0x66, 0x74, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x2e, 0x2f, 0x61, 0x70, 0x69,
	0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x2f, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x62, 0x6c, 0x6f, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDescOnce sync.Once
	file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDescData = file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDesc
)

func file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDescGZIP() []byte {
	file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDescOnce.Do(func() {
		file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDescData)
	})
	return file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDescData
}

var file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_goTypes = []interface{}{
	(*DraftBlogRequest)(nil), // 0: blog_svc.DraftBlogRequest
	(*BlogResponse)(nil),     // 1: blog_svc.BlogResponse
	(*Blog)(nil),             // 2: blog_svc.Blog
	(*Block)(nil),            // 3: blog_svc.Block
	(*Data)(nil),             // 4: blog_svc.Data
	(*Tunes)(nil),            // 5: blog_svc.Tunes
}
var file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_depIdxs = []int32{
	2, // 0: blog_svc.DraftBlogRequest.blog:type_name -> blog_svc.Blog
	2, // 1: blog_svc.BlogResponse.blog:type_name -> blog_svc.Blog
	3, // 2: blog_svc.Blog.Blocks:type_name -> blog_svc.Block
	4, // 3: blog_svc.Block.Data:type_name -> blog_svc.Data
	5, // 4: blog_svc.Block.Tunes:type_name -> blog_svc.Tunes
	0, // 5: blog_svc.BlogService.DraftBlog:input_type -> blog_svc.DraftBlogRequest
	1, // 6: blog_svc.BlogService.DraftBlog:output_type -> blog_svc.BlogResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_init() }
func file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_init() {
	if File_apis_serviceconn_gateway_blog_pb_gw_blog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DraftBlogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tunes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_goTypes,
		DependencyIndexes: file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_depIdxs,
		MessageInfos:      file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_msgTypes,
	}.Build()
	File_apis_serviceconn_gateway_blog_pb_gw_blog_proto = out.File
	file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_rawDesc = nil
	file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_goTypes = nil
	file_apis_serviceconn_gateway_blog_pb_gw_blog_proto_depIdxs = nil
}
