DROP TABLE IF EXISTS USER_INTEREST;
DROP TABLE IF EXISTS INTEREST;
DROP TABLE IF EXISTS PAYMENT_INFO;
DROP TABLE IF EXISTS USER_EXTERNAL_LOGIN;
DROP TABLE IF EXISTS USER_ACCOUNT_LOG;
DROP TABLE IF EXISTS USER_ACCOUNT_STATUS;
DROP TABLE IF EXISTS PERMISSIONS_GRANTED;
DROP TABLE IF EXISTS PERMISSIONS;
DROP TABLE IF EXISTS USER_AUTH_INFO;
DROP TABLE IF EXISTS EMAIL_VALIDATION_STATUS;
DROP TABLE IF EXISTS logged_in_devices;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS USER_ACCOUNT;
DROP TABLE IF EXISTS USER_ROLE;
DROP TABLE IF EXISTS user_status;
DROP TABLE IF EXISTS auth_provider;

